# Generated by Django 4.0.1 on 2022-01-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_unidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='idade',
            field=models.IntegerField(),
        ),
    ]
